# Generated by Django 5.1.4 on 2024-12-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
